module.exports = [
  {
    title:"Marc Andreessen: Future of the Internet, Technology, and AI | Lex Fridman Podcast #386",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title: "IELTS English Podcast - Speaking Topic: Technology",
    channel: "IELTS Plus",
    channelViewCount: "890125",
    subscriberCount: "33700",
    country: "KR",
  },
  {
    title:"The 3 Year AI Reset: How To Get Ahead While Others Lose Their Job (Prepare Now) | Emad Mostaque",
    channel: "Tom Bilyeu",
    channelViewCount: "426767539",
    subscriberCount: "4120000",
    country: "US",
  },
  {
    title: "Is technology harmful to youngsters? - 6 Minute English",
    channel: "BBC Learning English",
    channelViewCount: "328506842",
    subscriberCount: "6320000",
    country: "GB",
  },
  {
    title: "Jason Pontin: Can technology solve our big problems?",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title: "Elon Musk: The future we&#39;re building -- and boring | TED",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title: "Asking Doctor Mike About Health in Technology",
    channel: "WVFRM Podcast",
    channelViewCount: "51470083",
    subscriberCount: "378000",
    country: "US",
  },
  {
    title:
      "Falling in Love with Web Development | Kyle Cook - @WebDevSimplified | Beyond Coding Podcast #75",
    channel: "Beyond Coding",
    channelViewCount: "405837",
    subscriberCount: "14500",
    country: "NL",
  },
  {
    title:"BOX SET: 6 Minute English - Internet and Technology English mega-class! One hour of new vocabulary!",
    channel: "BBC Learning English",
    channelViewCount: "328506842",
    subscriberCount: "6320000",
    country: "GB",
  },
  {
    title:"Elon Musk: War, AI, Aliens, Politics, Physics, Video Games, and Humanity | Lex Fridman Podcast #400",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title:"What&#39;s The Next Game-Changing Technology? With Matt Ferrell | The PLUS Podcast",
    channel: "Everything Electric Show",
    channelViewCount: "9450063",
    subscriberCount: "90900",
    country: "GB",
  },
  {
    title: "You probably won’t survive 2024... Top 10 Tech Trends",
    channel: "Fireship",
    channelViewCount: "397639641",
    subscriberCount: "2920000",
    country: "US",
  },
  {
    title:"Why Quantum Tech Will Change Our Future: The Day Tomorrow Began Podcast",
    channel: "The University of Chicago",
    channelViewCount: "55450626",
    subscriberCount: "243000",
    country: "US",
  },
  {
    title:"Saket Modi Explains Behind the Scenes of Blockchain, Web3, Crypto World | The Ranveer Show 204",
    channel: "BeerBiceps",
    channelViewCount: "1450251076",
    subscriberCount: "7080000",
    country: "IN",
  },
  {
    title:"The Next Global Superpower Isn&#39;t Who You Think | Ian Bremmer | TED",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title:"Randall Carlson &amp; Graham Hancock on Lost Technology and the Great Pyramids",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title: "Learn English with the JOE ROGAN PODCAST — Elon Musk",
    channel: "Learn English With TV Series",
    channelViewCount: "167234192",
    subscriberCount: "8720000",
    country: "US",
  },
  {
    title: "Rishi Sunak &amp; Elon Musk: Talk AI, Tech &amp; the Future",
    channel: "Rishi Sunak",
    channelViewCount: "140139757",
    subscriberCount: "640000",
    country: "GB",
  },
  {
    title: "OpenAI CEO on Artificial Intelligence Changing Society",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title: "3 Tech Podcasts to Binge Listen | 2022 Best Tech Podcasts",
    channel: "Parker Rex",
    channelViewCount: "280329",
    subscriberCount: "4880",
    country: "US",
  },
  {
    title: "Tech Expert Warns of AI&#39;s Potentially Dangerous Capabilities",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title:"Hacker Saket Modi Returns: New Cyber Risks, Identity Thefts, Deep Fake Horrors | TRS 374",
    channel: "BeerBiceps",
    channelViewCount: "1450251076",
    subscriberCount: "7080000",
    country: "IN",
  },
  {
    title: "Is Mind Reading the Future of Technology?",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title:"Best Of: The Most Amazing — and Dangerous — Technology in the World",
    channel: "New York Times Podcasts",
    channelViewCount: "5440544",
    subscriberCount: "48900",
    country: "US",
  },
  {
    title: "Think Fast, Talk Smart: Communication Techniques",
    channel: "Stanford Graduate School of Business",
    channelViewCount: "146574771",
    subscriberCount: "2080000",
    country: "US",
  },
  {
    title:"Elon Musk talks Twitter, Tesla and how his brain works — live at TED2022",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title:"Michio Kaku: Future of Humans, Aliens, Space Travel &amp; Physics | Lex Fridman Podcast #45",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title: "Joe Rogan Experience #1470 - Elon Musk",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title:"Top 10 Technologies To Learn In 2023 | Trending Technologies In 2023 | Simplilearn",
    channel: "Simplilearn",
    channelViewCount: "342906388",
    subscriberCount: "3850000",
    country: "US",
  },
  {
    title: "Six key technology trends for 2023 — Thoughtworks Technology Podcast",
    channel: "Thoughtworks",
    channelViewCount: "7771319",
    subscriberCount: "39000",
    country: "Unknown",
  },
  {
    title:"Sam Altman: OpenAI CEO on GPT-4, ChatGPT, and the Future of AI | Lex Fridman Podcast #367",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title: "Expert Reveals The Pyramids LOST Technology",
    channel: "FLAGRANT",
    channelViewCount: "370509265",
    subscriberCount: "1570000",
    country: "US",
  },
  {
    title: "Speakout Pre-intermediate Video Podcast Unit 11 Technology",
    channel: "PearsonELTSpeakout",
    channelViewCount: "4977162",
    subscriberCount: "27000",
    country: "Unknown",
  },
  {
    title: "IELTS Listening Practice: Technology Conversation | Podcast Video",
    channel: "Magoosh IELTS",
    channelViewCount: "843369",
    subscriberCount: "31400",
    country: "US",
  },
  {
    title: "Joe Rogan Experience #1309 - Naval Ravikant",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title:"MICHELLE OBAMA Opens Up On Her 8 Years In The White House: &quot;We Know Too Much.&quot;",
    channel: "Jay Shetty Podcast",
    channelViewCount: "209059573",
    subscriberCount: "2530000",
    country: "US",
  },
  {
    title:"AI and the future of humanity | Yuval Noah Harari at the Frontiers Forum",
    channel: "Yuval Noah Harari ",
    channelViewCount: "38760056",
    subscriberCount: "648000",
    country: "Unknown",
  },
  {
    title:"Improved Quantum Computing, Artificial Intelligence &amp; Cyber Warfares With Abhijit Chavda | TRS 341",
    channel: "BeerBiceps",
    channelViewCount: "1450251076",
    subscriberCount: "7080000",
    country: "IN",
  },
  {
    title: "Brain Implants, Space Balloons, and the Technology of the Future",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title: "LEARN ENGLISH PODCAST: PHONES AND SOCIAL MEDIA (WITH SUBTITLES)",
    channel: "To Fluency",
    channelViewCount: "34881145",
    subscriberCount: "1130000",
    country: "US",
  },
  {
    title:"Sam Altman: OpenAI, GPT-5, Sora, Board Saga, Elon Musk, Ilya, Power &amp; AGI | Lex Fridman Podcast #419",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title: "25 Year Old Cyber Security Engineer On His Way To Be A Millionaire",
    channel: "Tech Is The New Black",
    channelViewCount: "8854719",
    subscriberCount: "134000",
    country: "US",
  },
  {
    title:"Dark Side Of AI Explained - S. Maheshwari on Aliens &amp; AI, Future Of Jobs &amp; More | TRSH 175",
    channel: "Ranveer Allahbadia",
    channelViewCount: "1181301486",
    subscriberCount: "7400000",
    country: "IN",
  },
  {
    title:"After watching this, your brain will not be the same | Lara Boyd | TEDxVancouver",
    channel: "TEDx Talks",
    channelViewCount: "7778775514",
    subscriberCount: "40400000",
    country: "Unknown",
  },
  {
    title: "Behind the Plan of the World Economic Forum&#39;s Smart Cities",
    channel: "Shawn Ryan Clips",
    channelViewCount: "1091815364",
    subscriberCount: "1690000",
    country: "US",
  },
  {
    title:"How to Make Learning as Addictive as Social Media | Luis Von Ahn | TED",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title: "AI Technology Karegi Insaano Pe Raaj ? Ft @TechMasterAK | Realhit",
    channel: "RealHit",
    channelViewCount: "853857455",
    subscriberCount: "5220000",
    country: "IN",
  },
  {
    title:"TikTok CEO Shou Chew on Its Future — and What Makes Its Algorithm Different | Live at TED2023",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title: "How to Get Your Brain to Focus | Chris Bailey | TEDxManchester",
    channel: "TEDx Talks",
    channelViewCount: "7778775514",
    subscriberCount: "40400000",
    country: "Unknown",
  },
  {
    title: "Meta Just Achieved Mind-Reading Using AI",
    channel: "ColdFusion",
    channelViewCount: "467813734",
    subscriberCount: "4740000",
    country: "AU",
  },
  {
    title:"Zoom Test: Samsung Galaxy S24 Ultra vs. Honor Magic 6 Pro 📸 #shorts",
    channel: "Tbreak Media",
    channelViewCount: "17823798",
    subscriberCount: "26400",
    country: "AE",
  },
  {
    title: "The Only People Joe Rogan Will NEVER Podcast With",
    channel: "Louaista",
    channelViewCount: "1262059386",
    subscriberCount: "1320000",
    country: "US",
  },
  {
    title: "Miley Cyrus Disses Joe Rogan on his Podcast",
    channel: "Rogan Shorts",
    channelViewCount: "1158513342",
    subscriberCount: "764000",
    country: "CA",
  },
  {
    title: "LEARN ENGLISH PODCAST: PHONES AND SOCIAL MEDIA (WITH SUBTITLES)",
    channel: "To Fluency",
    channelViewCount: "34881145",
    subscriberCount: "1130000",
    country: "US",
  },
  {
    title: "Meta Just Achieved Mind-Reading Using AI",
    channel: "ColdFusion",
    channelViewCount: "467813734",
    subscriberCount: "4740000",
    country: "AU",
  },
  {
    title:"Why Marques Brownlee a.k.a MKBHD Carry Two Phones Always #shorts #podcast #mkbhd #marquesbrownlee",
    channel: "Short Podcasts",
    channelViewCount: "61723545",
    subscriberCount: "31900",
    country: "IN",
  },
  {
    title: "How to Learn Skills Faster | Huberman Lab Podcast",
    channel: "Andrew Huberman",
    channelViewCount: "266770793",
    subscriberCount: "5210000",
    country: "US",
  },
  {
    title:"Improved Quantum Computing, Artificial Intelligence &amp; Cyber Warfares With Abhijit Chavda | TRS 341",
    channel: "BeerBiceps",
    channelViewCount: "1450251076",
    subscriberCount: "7080000",
    country: "IN",
  },
  {
    title:"Why Is Water So Remarkable? | Neil deGrasse Tyson | Joe Rogan Experience Podcast",
    channel: "Wonder Science",
    channelViewCount: "82155248",
    subscriberCount: "93700",
    country: "Unknown",
  },
  {
    title: "Speakout Pre-intermediate Video Podcast Unit 11 Technology",
    channel: "PearsonELTSpeakout",
    channelViewCount: "4977162",
    subscriberCount: "27000",
    country: "Unknown",
  },
  {
    title:
      "Ep.37 SPACE IS CRAZY!! #ninjasarebutterflies #podcast #sundaycool #comedy",
    channel: "Sunday Cool",
    channelViewCount: "480525416",
    subscriberCount: "1090000",
    country: "US",
  },
  {
    title:
      "Elvish Yadav Arrested | YouTuber Elvish Yadav Arrested In Snake Venom-Rave Party Case",
    channel: "NDTV",
    channelViewCount: "5465162003",
    subscriberCount: "13200000",
    country: "IN",
  },
  {
    title:
      "Talking with Christopher Dunn! UnchartedX Podcast - Ancient High Technology around the world",
    channel: "UnchartedX",
    channelViewCount: "40423276",
    subscriberCount: "478000",
    country: "US",
  },
  {
    title:
      "Marques still uses the Apple M1 #mkbhd #podcast #marquesbrownlee #apple",
    channel: "Waveform Clips",
    channelViewCount: "81434753",
    subscriberCount: "460000",
    country: "US",
  },
  {
    title: "FIRE Video Podcast Setup",
    channel: "Ben Johnson",
    channelViewCount: "10275302",
    subscriberCount: "194000",
    country: "US",
  },
  {
    title: "Brain Implants, Space Balloons, and the Technology of the Future",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title:
      "Six key technology trends for 2023 — Thoughtworks Technology Podcast",
    channel: "Thoughtworks",
    channelViewCount: "7771319",
    subscriberCount: "39000",
    country: "Unknown",
  },
  {
    title: "How to Upload a Podcast to Spotify #shorts",
    channel: "Riversidefm",
    channelViewCount: "5567880",
    subscriberCount: "34800",
    country: "US",
  },
  {
    title: "OpenAI CEO, CTO on risks and how AI will reshape society",
    channel: "ABC News",
    channelViewCount: "14386378252",
    subscriberCount: "16300000",
    country: "US",
  },
  {
    title:
      "Ep.39 UFO’s shining Lasers at people?? #ninjasarebutterflies #podcast #sundaycool #comedy",
    channel: "Sunday Cool",
    channelViewCount: "480525416",
    subscriberCount: "1090000",
    country: "US",
  },
  {
    title:
      "Chris Kyle &quot;The Legend&quot; Says His Shot Was Just An Accident #war #army #podcast",
    channel: "Wagon Military",
    channelViewCount: "31715989",
    subscriberCount: "58900",
    country: "Unknown",
  },
  {
    title: "Here’s how you can edit a podcast in less than a minute #shorts",
    channel: "The Verge",
    channelViewCount: "1025929404",
    subscriberCount: "3350000",
    country: "US",
  },
  {
    title: "3 Tech Podcasts to Binge Listen | 2022 Best Tech Podcasts",
    channel: "Parker Rex",
    channelViewCount: "280329",
    subscriberCount: "4880",
    country: "US",
  },
  {
    title: "Easy 2 Person Podcast Setup for Beginners (Remote or In Person)",
    channel: "Riversidefm",
    channelViewCount: "5567880",
    subscriberCount: "34800",
    country: "US",
  },
  {
    title: "How did he get away with it",
    channel: "P1 with Matt & Tommy",
    channelViewCount: "78228353",
    subscriberCount: "462000",
    country: "GB",
  },
  {
    title: "StarTalk Podcast: Physics All Around Us, with Neil deGrasse Tyson",
    channel: "StarTalk",
    channelViewCount: "392066526",
    subscriberCount: "2910000",
    country: "US",
  },
  {
    title: "IELTS Listening Practice: Technology Conversation | Podcast Video",
    channel: "Magoosh IELTS",
    channelViewCount: "843369",
    subscriberCount: "31400",
    country: "US",
  },
  {
    title:
      "Best CHEAP Podcast Setup for Beginners (Everything You Need to Start!)",
    channel: "Think Media",
    channelViewCount: "331771070",
    subscriberCount: "2870000",
    country: "US",
  },
  {
    title:
      "Ep.43 French Submarine captures pictures of UFO??#ninjasarebutterflies #podcast #sundaycool #comedy",
    channel: "Sunday Cool",
    channelViewCount: "480525416",
    subscriberCount: "1090000",
    country: "US",
  },
  {
    title:
      "#2900Rpm #texmo #monoblock #0.5hp #90fut_hed #selfpriming #youtubeshorts #podcast #pressure_test",
    channel: "SANU YT SAGAR SHOTS",
    channelViewCount: "1027853",
    subscriberCount: "3180",
    country: "IN",
  },
  {
    title:
      "SPANISH LISTENING PRACTICE | What do you think about this tech? [Spanish Podcast]",
    channel: "How to Spanish Lessons & Podcast",
    channelViewCount: "4442185",
    subscriberCount: "72100",
    country: "MX",
  },
  {
    title: "AI Technology Karegi Insaano Pe Raaj ? Ft @TechMasterAK | Realhit",
    channel: "RealHit",
    channelViewCount: "853857455",
    subscriberCount: "5220000",
    country: "IN",
  },
  {
    title: "The Libre Podcast (Formerly Freedom of Technology)",
    channel: "Mental Outlaw",
    channelViewCount: "117643975",
    subscriberCount: "598000",
    country: "US",
  },
  {
    title: "Joe Rogan Experience #2117 - Ray Kurzweil",
    channel: "PowerfulJRE",
    channelViewCount: "3457086352",
    subscriberCount: "16400000",
    country: "Unknown",
  },
  {
    title: "Adobe Podcast AI Recreates Your Words",
    channel: "Sound Speeds",
    channelViewCount: "2196319",
    subscriberCount: "19900",
    country: "US",
  },
  {
    title:
      "Why not find the wall of gog Magog |Sahil Adeem Podcast @Nadiraliofficial",
    channel: "Motivated Muslim",
    channelViewCount: "15619691",
    subscriberCount: "87400",
    country: "PK",
  },
  {
    title:
      "Ray Kurzweil: Singularity, Superintelligence, and Immortality | Lex Fridman Podcast #321",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title:
      "Dark Side Of AI Explained - S. Maheshwari on Aliens &amp; AI, Future Of Jobs &amp; More | TRSH 175",
    channel: "Ranveer Allahbadia",
    channelViewCount: "1181301486",
    subscriberCount: "7400000",
    country: "IN",
  },
  {
    title: "How to Start a Video Podcast from A to Z",
    channel: "Full Time Filmmaker",
    channelViewCount: "142974626",
    subscriberCount: "2030000",
    country: "US",
  },
  {
    title:
      "Dennis Whyte: Nuclear Fusion and the Future of Energy | Lex Fridman Podcast #353",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
  {
    title: "The Bid investment podcast trailer",
    channel: "BlackRock",
    channelViewCount: "4715022",
    subscriberCount: "28900",
    country: "US",
  },
  {
    title:
      "Possible type 2 civilization - The Joe Rogan Experience #1828 - Michio Kaku #podcast #technology",
    channel: "hektic",
    channelViewCount: "37063752",
    subscriberCount: "28200",
    country: "Unknown",
  },
  {
    title: "Discovering the Power of Technology: Separating Good from Bad",
    channel: "The11thCommandment",
    channelViewCount: "2827381",
    subscriberCount: "37000",
    country: "US",
  },
  {
    title: "Renaissance Technologies (Audio)",
    channel: "Acquired",
    channelViewCount: "32423685",
    subscriberCount: "78800",
    country: "US",
  },
  {
    title:
      "Find the full convo on my channel or Spotify: &quot;Big Technology Podcast: The U.S and Tech After Trump&quot;",
    channel: "Alex Kantrowitz",
    channelViewCount: "555589",
    subscriberCount: "3770",
    country: "US",
  },
  {
    title:
      "LEARN ENGLISH PODCAST: YOU MUST DO THIS TO IMPROVE FAST (+ BEST METHOD)",
    channel: "To Fluency",
    channelViewCount: "34881145",
    subscriberCount: "1130000",
    country: "US",
  },
  {
    title:
      "trump on meeting with heavyweights #india #technology  #realestate #podcast #business",
    channel: "Ameer hamza",
    channelViewCount: "13095",
    subscriberCount: "9",
    country: "Unknown",
  },
  {
    title: "TOP 7 Technology Trends in 2023",
    channel: "TechMagelanic",
    channelViewCount: "476869",
    subscriberCount: "10000",
    country: "US",
  },
  {
    title: "What really matters at the end of life | BJ Miller | TED",
    channel: "TED",
    channelViewCount: "2675381559",
    subscriberCount: "24100000",
    country: "US",
  },
  {
    title:"Brett Johnson: US Most Wanted Cybercriminal | Lex Fridman Podcast #272",
    channel: "Lex Fridman",
    channelViewCount: "633874607",
    subscriberCount: "3820000",
    country: "US",
  },
]
